spring.application.name=spring-security-tutorial

#spring.security.user.name=jack
#spring.security.user.password=jack123
#spring.security.user.roles=ADMIN

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/spring-security-7?useSSL=false
spring.datasource.username=jackr
spring.datasource.password=mysql@123

spring.jpa.hibernate.ddl-auto=update
