spring.application.name=spring-security-tutorial

#spring.security.user.name=jack
#spring.security.user.password=jack123
#spring.security.user.roles=ADMIN

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/spring-security-7?useSSL=false
spring.datasource.username=jackr
spring.datasource.password=mysql@123

spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=6ae2ee6cc9d09492e9fc86e2f30865d67d7efa7b23e7eb1c30d5f3cccf862e73
app.jwt.expiration-milliseconds=604800000
